# 1. SERVER SETTINGS
server.port=8080

# 2. FILE UPLOAD LIMITS (Critical for JPlag ZIPs)
# This prevents "File too large" errors when students upload big projects
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# 3. DATABASE (PostgreSQL - Local)
spring.datasource.url=jdbc:postgresql://localhost:5432/plagiarism_db
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# 4. LOGGING (Helpful for Member 4 to see JPlag progress)
logging.level.com.project=DEBUG